openapi: 3.0.0
info:
  title: Inventory Management System API
  description: API documentation for the Inventory Management System
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local development server
paths:
  /users:
    post:
      summary: Create a new user
      description: Registers a new user in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phone_number:
                  type: string
                role:
                  type: string
                  enum: ["Program Manager", "Inventory Manager"]
      responses:
        "201":
          description: User created successfully
        "400":
          description: Bad request
  /inventory:
    get:
      summary: Get all inventory items
      description: Returns a list of all inventory items.
      responses:
        "200":
          description: Successful operation
        "500":
          description: Internal server error
    post:
      summary: Add a new inventory item
      description: Adds a new item to the inventory.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                quantity:
                  type: integer
      responses:
        "201":
          description: Item added successfully
        "400":
          description: Bad request
